//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Templates.Alloy.Views.Blocks {
    
    
    public partial class BlockPreview {
        
        /// <summary>
        /// FullWidthPreviewPropertyHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Templates.Alloy.Business.WebControls.TemplateHint FullWidthPreviewPropertyHint;
        
        /// <summary>
        /// FullWidthPreviewProperty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Web.WebControls.Property FullWidthPreviewProperty;
        
        /// <summary>
        /// TwoThirdsWidthPreviewPropertyHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Templates.Alloy.Business.WebControls.TemplateHint TwoThirdsWidthPreviewPropertyHint;
        
        /// <summary>
        /// TwoThirdsWidthPreviewProperty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Web.WebControls.Property TwoThirdsWidthPreviewProperty;
        
        /// <summary>
        /// HalfWidthPreviewPropertyHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Templates.Alloy.Business.WebControls.TemplateHint HalfWidthPreviewPropertyHint;
        
        /// <summary>
        /// HalfWidthPreviewProperty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Web.WebControls.Property HalfWidthPreviewProperty;
        
        /// <summary>
        /// OneThirdWidthPreviewPropertyHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Templates.Alloy.Business.WebControls.TemplateHint OneThirdWidthPreviewPropertyHint;
        
        /// <summary>
        /// OneThirdWidthPreviewProperty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EPiServer.Web.WebControls.Property OneThirdWidthPreviewProperty;
    }
}
